spring.application.name=tila

api.security.token.secret="Cucamole@123"

spring.datasource.url=jdbc:postgresql://localhost:5433/TilaDB
spring.datasource.username=postgres
spring.datasource.password=Cucamole@123
spring.datasource.driverClassName=org.postgresql.Driver

# Configuracao do JPA e Hibernate
# 'update' \uFFFD bom para desenvolvimento, mas em producao use 'validate' ou remova.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true